Repository knative-extensions/eventing-redis, pull requests merged in 2021-06, with the labels that each got.

#157 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/condition_types.go
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/duck/register.go
  vendor/knative.dev/pkg/apis/duck/v1/register.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/register.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/factory/factory.go
  vendor/knative.dev/pkg/configmap/manual_watcher.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/pkg/system/env.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/tinterface.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/webhook/admission.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#159 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#161 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#160 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#158 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#163 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#165 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#164 Move tls cert into a secret
  source/config/500-controller.yaml
  source/config/tls-secret.yaml
  source/pkg/reconciler/streamsource/config.go
  source/pkg/reconciler/streamsource/controller.go
Labels: approved, cla: yes, lgtm, size/S

#167 Revert "Move tls cert into a secret (#164)"
  source/config/500-controller.yaml
  source/config/tls-secret.yaml
  source/pkg/reconciler/streamsource/config.go
  source/pkg/reconciler/streamsource/controller.go
Labels: approved, cla: yes, lgtm, size/S

#168 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#169 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#173 Converting TLS Cert's config map into secret
  source/config/500-controller.yaml
  source/config/config-tls.yaml
  source/config/tls-secret.yaml
  source/pkg/reconciler/streamsource/config.go
  source/pkg/reconciler/streamsource/controller.go
  source/pkg/reconciler/streamsource/streamsource.go
Labels: approved, cla: yes, lgtm, size/M

#174 update readme
  source/README.md
Labels: approved, cla: yes, lgtm, size/XS

#177 Converting TLS cert's config map into a secret (cont.)
  sink/README.md
  sink/config/500-controller.yaml
  sink/config/config-tls.yaml
  sink/config/tls-secret.yaml
  sink/pkg/reconciler/streamsink/config.go
  sink/pkg/reconciler/streamsink/controller.go
  sink/pkg/reconciler/streamsink/streamsink.go
  source/README.md
Labels: approved, cla: yes, lgtm, size/M

#172 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/apiserver/pkg/storage/names/LICENSE
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/storage/names/generate.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#178 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#179 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_conversion.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/api_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#180 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-cleanhttp/handlers.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/client.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/go-retryablehttp/roundtripper.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#181 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#182 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#183 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: approved, cla: yes, lgtm, size/XS

#184 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#185 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS
