Repository knative-extensions/eventing-redis, pull requests merged in 2021-05, with the labels that each got.

#138 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, size/S

#139 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/fake/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/pingsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1/sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1beta1/sources_client.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#140 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#141 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#144 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: cla: yes, size/XS

#145 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#146 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#147 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#142 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#148 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#149 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XS

#150 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/knative.dev/eventing/pkg/adapter/v2/cloudevents.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/test/lib/resources/eventing.go
  vendor/knative.dev/eventing/test/lib/test_runner.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#156 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#155 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#153 adding dialusername to support redis v6
  source/README.md
  source/pkg/adapter/adapter.go
Labels: approved, cla: yes, lgtm, size/S
