Repository knative-extensions/eventing-redis, pull requests merged in 2021-01, with the labels that each got.

#55 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#56 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#57 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#58 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#59 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#60 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/eventing/pkg/kncloudevents/message_receiver.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/network/handlers/drain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#67 Upgrading engineerd/setup-kind to v0.5.0 due to deprecation in Github action environment
  .github/workflows/kind-e2e.yaml
Labels: approved, cla: yes, lgtm, size/XS

#62 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#64 [] Upgrade to latest dependencies
  go.mod
  go.sum
  sink/pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  sink/pkg/client/injection/informers/factory/filtered/filtered_factory.go
  sink/pkg/client/injection/informers/sinks/v1alpha1/redisstreamsink/filtered/fake/fake.go
  sink/pkg/client/injection/informers/sinks/v1alpha1/redisstreamsink/filtered/redisstreamsink.go
  sink/pkg/client/injection/reconciler/sinks/v1alpha1/redisstreamsink/controller.go
  source/pkg/client/injection/informers/factory/filtered/fake/fake_filtered_factory.go
  source/pkg/client/injection/informers/factory/filtered/filtered_factory.go
  source/pkg/client/injection/informers/sources/v1alpha1/redisstreamsource/filtered/fake/fake.go
  source/pkg/client/injection/informers/sources/v1alpha1/redisstreamsource/filtered/redisstreamsource.go
  source/pkg/client/injection/reconciler/sources/v1alpha1/redisstreamsource/controller.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/duck/channel.go
  vendor/knative.dev/eventing/pkg/duck/listable.go
  vendor/knative.dev/eventing/pkg/duck/subscriber.go
  vendor/knative.dev/eventing/test/lib/duck/resource_creators.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#63 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/client/listers/autoscaling/v1alpha1/metric.go
  vendor/knative.dev/serving/pkg/client/listers/autoscaling/v1alpha1/podautoscaler.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/listers/serving/v1alpha1/domainmapping.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#68 Changes for cloud based Redis instances that need config-tls
  source/README.md
  source/config/config-redis.yaml
  source/config/config-tls.yaml
Labels: approved, cla: yes, lgtm, size/S

#72 [Automated] Format markdown
  source/README.md
Labels: approved, cla: yes, lgtm, size/S

#73 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
