Repository knative-extensions/eventing-redis, pull requests merged in 2021-08, with the labels that each got.

#199 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#200 bump go to 1.16
  .github/workflows/kind-e2e.yaml
  go.mod
  go.sum
Labels: cla: yes, lgtm, approved, size/XS

#201 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#202 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#203 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  sink/pkg/client/injection/client/client.go
  sink/pkg/client/injection/informers/sinks/v1alpha1/redisstreamsink/filtered/redisstreamsink.go
  sink/pkg/client/injection/informers/sinks/v1alpha1/redisstreamsink/redisstreamsink.go
  source/pkg/client/injection/client/client.go
  source/pkg/client/injection/informers/sources/v1alpha1/redisstreamsource/filtered/redisstreamsource.go
  source/pkg/client/injection/informers/sources/v1alpha1/redisstreamsource/redisstreamsource.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/client/injection/kube/client/client_expansion.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset_expansion.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/network/handlers/error.go
  vendor/knative.dev/pkg/tracing/zipkin.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: cla: yes, size/XL, lgtm, approved

#205 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: cla: yes, lgtm, approved, size/XS

#207 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/test/helpers/name.go
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#209 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#211 Update deps and use controller.Impl tracker
  go.mod
  go.sum
  source/pkg/reconciler/streamsource/controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved
