Repository knative-extensions/eventing-redis, pull requests merged in 2021-11, with the labels that each got.

#245 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#246 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: cla: yes, size/M, lgtm, approved

#247 Document maturity levels in sandbox
  README.md
Labels: cla: yes, lgtm, approved, size/XS

#249 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, size/S, lgtm, approved

#251 [main] Update actions
  .github/workflows/knative-verify.yaml
Labels: cla: yes, lgtm, approved, size/XS

#252 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/test/lib/creation.go
  vendor/knative.dev/eventing/test/lib/duck/resource_getters.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: cla: yes, size/XL, lgtm, approved

#253 [main] Update community files
  OWNERS_ALIASES
Labels: cla: yes, lgtm, approved, size/XS
