Repository knative-extensions/eventing-redis, pull requests merged in 2022-10, with the labels that each got.

#384 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#389 Update deps and bump cloudevents/sdk-go/sql to 52b12276cc4a
  go.mod
  go.sum
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_config_set.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserialization_options.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserializer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/error_strategy.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/lexer_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/ll1_analyzer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/recognizer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/semantic_context.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/tree.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils_set.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/README.md
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParser.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParserLexer.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_base_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_lexer.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_parser.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_visitor.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#390 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#388 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/version/version.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#391 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#394 update deps
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/S, lgtm, approved

#395 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#396 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#397 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#398 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: size/S, lgtm, approved

#399 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/XS

#400 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#401 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/modules.txt
Labels: size/M, lgtm, approved

#386 XINFO GROUPS accepts response of 12 entries
  pkg/source/redis/scan.go
Labels: lgtm, approved, size/XS

#402 Correct source & sink links in root readme
  README.md
Labels: lgtm, approved, size/XS

#403 Correct paths in sink & source readmes
  config/sink/README.md
  config/source/README.md
Labels: size/M, lgtm, approved

#404 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/modules.txt
Labels: size/M, lgtm, approved
