Repository knative-extensions/eventing-redis, pull requests merged in 2023-04, with the labels that each got.

#435 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/kncloudevents/retries.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/L, lgtm, approved

#439 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#438 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: size/M, lgtm, approved

#440 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#441 chore: migrate from k8s.gcr.io to registry.k8s.io
  config/sink/config-observability.yaml
  config/source/config-observability.yaml
Labels: ok-to-test, lgtm, approved, size/XS

#443 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
