Repository knative-extensions/eventing-redis, pull requests merged in 2024-01, with the labels that each got.

#507 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#508 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#509 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#510 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#511 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#512 Remove unneeded Go toolchain directive
  go.mod
Labels: lgtm, approved, size/XS

#514 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: size/S, lgtm, approved

#517 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/register.go
  vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
  vendor/modules.txt
Labels: size/M, lgtm, approved
